#!/bin/zsh

set -e

RUNNING_DGRAPH_CONTAINERS=$(docker-compose ps -q 2>/dev/null | wc -l)

# dgraph only accepts admin REST requests from whitelisted IP's, hence the added
# complexity of explicit docker networks and IP address fetching.

echo $RUNNING_DGRAPH_CONTAINERS

if [ "$RUNNING_DGRAPH_CONTAINERS" -ne 3 ]; then
	docker network create dgraph_dev || true
	WHITELISTED=$(docker network inspect dgraph_dev | jq '.[0].IPAM.Config[0].Gateway')
	export WHITELISTED
	docker-compose up -d
fi
